/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PGUI;

import ProjectDB.CoursesDB;
import ProjectDB.DepartmentDB;
import ProjectDB.FacultyDB;
import ProjectDB.StudentDB;
import ProjectDB.TeacherDB;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapping.Course;
import mapping.Departments;
import mapping.Faculty;
import mapping.Student;
import mapping.Teacher;


/**
 *
 * @author GRACE
 */
public class GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        changedptCombo();
        combobox();
        comboCourse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Department = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sid = new javax.swing.JTextField();
        Sname = new javax.swing.JTextField();
        Screate = new javax.swing.JButton();
        Read = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Stable = new javax.swing.JTable();
        Combo2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Combo4 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ccode = new javax.swing.JTextField();
        CName = new javax.swing.JTextField();
        Ccreate = new javax.swing.JButton();
        Cread = new javax.swing.JButton();
        Cupdate = new javax.swing.JButton();
        Cdelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ctable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Did = new javax.swing.JTextField();
        Dname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        Dcreate = new javax.swing.JButton();
        Dread = new javax.swing.JButton();
        Dupdate = new javax.swing.JButton();
        Ddelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Dtable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Fid = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Ftable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tsalary = new javax.swing.JTextField();
        Tid = new javax.swing.JTextField();
        degree = new javax.swing.JTextField();
        Tcreate = new javax.swing.JButton();
        Tread = new javax.swing.JButton();
        Tupdate = new javax.swing.JButton();
        Tdelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ttable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        Combo3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Tname1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        registration = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        stSearch = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        StudentCourseResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Departments");

        Sname.setText(" ");

        Screate.setText("Create");
        Screate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreateActionPerformed(evt);
            }
        });

        Read.setText("Read");
        Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Stable);

        jLabel15.setText("Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Sid)
                                        .addComponent(Sname, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                    .addComponent(Combo4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Screate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Read)
                                .addGap(49, 49, 49)
                                .addComponent(Update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Screate)
                    .addComponent(Read)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        Department.addTab("Student", jPanel1);

        jLabel7.setText("Code");

        jLabel8.setText("Name");

        Ccode.setText(" ");

        CName.setText(" ");

        Ccreate.setText("Create");
        Ccreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcreateActionPerformed(evt);
            }
        });

        Cread.setText("Read");
        Cread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreadActionPerformed(evt);
            }
        });

        Cupdate.setText("Update");
        Cupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CupdateActionPerformed(evt);
            }
        });

        Cdelete.setText("Delete");
        Cdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdeleteActionPerformed(evt);
            }
        });

        Ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(Ctable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ccode, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(CName)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Ccreate)
                        .addGap(18, 18, 18)
                        .addComponent(Cread)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cupdate)
                        .addGap(18, 18, 18)
                        .addComponent(Cdelete))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Ccode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ccreate)
                    .addComponent(Cread)
                    .addComponent(Cupdate)
                    .addComponent(Cdelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        Department.addTab("Courses", jPanel3);

        jLabel10.setText("Id");

        Name.setText("Name");

        Did.setText(" ");
        Did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DidActionPerformed(evt);
            }
        });

        Dname.setText(" ");

        jLabel11.setText("Faculty");

        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        Dcreate.setText("Create");
        Dcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcreateActionPerformed(evt);
            }
        });

        Dread.setText("Read");
        Dread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DreadActionPerformed(evt);
            }
        });

        Dupdate.setText("Update");
        Dupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DupdateActionPerformed(evt);
            }
        });

        Ddelete.setText("Delete");
        Ddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DdeleteActionPerformed(evt);
            }
        });

        Dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Dtable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(Name)
                                    .addComponent(jLabel11))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Dname, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(Did)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Dcreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dread)
                                .addGap(18, 18, 18)
                                .addComponent(Dupdate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ddelete))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dcreate)
                    .addComponent(Dread)
                    .addComponent(Dupdate)
                    .addComponent(Ddelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Department.addTab("Department", jPanel4);

        jLabel12.setText("Id");

        jLabel13.setText("Name");

        Fid.setText(" ");

        Fname.setText("  ");

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Read");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");

        jButton4.setText("Delete");

        Ftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(Ftable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(60, 60, 60)
                            .addComponent(Fid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(43, 43, 43)
                            .addComponent(Fname)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Fid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        Department.addTab("Faculty", jPanel5);

        jLabel4.setText("ID");

        jLabel5.setText("Name");

        jLabel6.setText("Salary");

        Tsalary.setText(" ");

        Tid.setText(" ");

        degree.setText(" ");
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });

        Tcreate.setText("Create");
        Tcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcreateActionPerformed(evt);
            }
        });

        Tread.setText("Read");
        Tread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreadActionPerformed(evt);
            }
        });

        Tupdate.setText("update");
        Tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TupdateActionPerformed(evt);
            }
        });

        Tdelete.setText("Delete");
        Tdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdeleteActionPerformed(evt);
            }
        });

        Ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Ttable);

        jLabel14.setText("Courses");

        Combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Degree");

        Tname1.setText(" ");
        Tname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tname1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tcreate)
                        .addGap(30, 30, 30)
                        .addComponent(Tread)
                        .addGap(37, 37, 37)
                        .addComponent(Tupdate)
                        .addGap(42, 42, 42)
                        .addComponent(Tdelete))
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tname1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Tsalary, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(degree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tcreate)
                    .addComponent(Tread)
                    .addComponent(Tupdate)
                    .addComponent(Tdelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Department.addTab("Teacher", jPanel2);

        jLabel17.setText("Student ID:");

        studentId.setText("  ");

        stSearch.setText("Search");
        stSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stSearchActionPerformed(evt);
            }
        });

        StudentCourseResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(StudentCourseResult);

        javax.swing.GroupLayout registrationLayout = new javax.swing.GroupLayout(registration);
        registration.setLayout(registrationLayout);
        registrationLayout.setHorizontalGroup(
            registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationLayout.createSequentialGroup()
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel17)
                        .addGap(65, 65, 65)
                        .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(stSearch))
                    .addGroup(registrationLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        registrationLayout.setVerticalGroup(
            registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stSearch)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        Department.addTab("Registrion", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Department)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void DidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DidActionPerformed

    private void ScreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreateActionPerformed
        // TODO add your handling code here:
        
        
         String Id=Sid.getText();
         String Name=Sname.getText();
         String Course=(String) Combo4.getSelectedItem();
         String Department=(String) Combo2.getSelectedItem();
         int row = Combo2.getSelectedIndex();
         int rowc= Combo4.getSelectedIndex();
         Student st = new Student();
         StudentDB Db=new StudentDB();
          Course c=new Course(); 
            CoursesDB cda= new CoursesDB();
            c=cda.CDisplay().get(rowc);
            st=Db.findByID(Id);
          if(st!=null){
              st.getRegCourses().add(c);
              Db.UpdateStudent(st);
          
          } else{
           DepartmentDB dDao = new DepartmentDB();
       
           Departments dp = new Departments();
           dp=dDao.DisplayD().get(row);
           st.setDepartment(dp);
          }
         
        
         
        
       
         
        
         
         
          
          JOptionPane.showMessageDialog(this,st+"Row Created" );
           
         
    }//GEN-LAST:event_ScreateActionPerformed

    private void ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadActionPerformed
        // TODO add your handling code here:
        
        StudentDB db= new StudentDB();
         List<Student> ls=new ArrayList<>();
         ls=db.DisplayStudents();
         DefaultTableModel model= new DefaultTableModel();
         Object cols[] = new Object[3];
         cols[0]="ID";
         cols[1]="Name";
         cols[2]="Department";
         model.setColumnIdentifiers(cols);
       for(Student s:ls){
       Object row[]=new Object[4];
                  row[0]=s.getNationalID();
                  row[1]=s.getName();
                  row[2]=s.getDepartment().getName();
                  
                  model.addRow(row);
       }
       Stable.setModel(model);
    }//GEN-LAST:event_ReadActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
      String Id=Sid.getText();
         String Name=Sname.getText();
         String Course=(String) Combo4.getSelectedItem();
         String Department=(String) Combo2.getSelectedItem();
   
        Departments dp = new Departments();
        
         Student st = new Student();
                
        
         st.setNationalID(Id);
         st.setName(Name);
         st.addCourse(new Course());
         st.setDepartment(dp);
       
         st.addCourse(new Course());
         st.setDepartment(dp);
        
         StudentDB Db=new StudentDB();
         Db.UpdateStudent(st);
         JOptionPane.showMessageDialog(this,st+"Row Updated" );
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         String Id=Sid.getText();
//         String Name=Sname.getText();
//         String Course=(String) Combo4.getSelectedItem();
//         String Department=(String) Combo2.getSelectedItem();
//      
//        Departments dp = new Departments();
         StudentDB Db=new StudentDB();
         Student st = new Student();
         st= Db.findByID(Id);
        
//         st.setNationalID(Id);
//         st.setName(Name);
//         st.addCourse(new Course());
//         st.setDepartment(dp);
//       
//         st.addCourse(new Course());
//         st.setDepartment(dp);
        
         
         Db.DeleleStudet(st);
         JOptionPane.showMessageDialog(this,st+"Row Deleted" );
    }//GEN-LAST:event_DeleteActionPerformed

    private void TcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcreateActionPerformed
        // TODO add your handling code here:
        String Id=Tid.getText();
        String Name=Tname1.getText();
        String Degree=degree.getText();
        String Salary=Tsalary.getText();
  
   
        
        Teacher t=new Teacher();
                
        
        t.setNationalID(Id);
        t.setName(Name);
        t.setDegree(Degree);
        t.setSalary(Salary);
        
         TeacherDB db=new TeacherDB();
         db.SaveTeacher(t);
         JOptionPane.showMessageDialog(this,t+"Row Created" );
         
        
    }//GEN-LAST:event_TcreateActionPerformed

    private void TreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreadActionPerformed
        // TODO add your handling code here:
        
        TeacherDB db=new TeacherDB();
         List<Teacher> ls=new ArrayList<>();
         ls=db.Display();
         DefaultTableModel model= new DefaultTableModel();
         Object cols[] = new Object[4];
         cols[0]="ID";
         cols[1]="Name";
         cols[2]="Degree";
         cols[3]="Salary";
        
         model.setColumnIdentifiers(cols);
       for(Teacher t:ls){
       Object row[]=new Object[4];
                  row[0]=t.getNationalID();
                  row[1]=t.getName();
                  row[2]=t.getDegree();
                  row[3]=t.getSalary();
                  
                  model.addRow(row);
       }
       Ttable.setModel(model);
    }//GEN-LAST:event_TreadActionPerformed

    private void TupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TupdateActionPerformed
        // TODO add your handling code here:
        
        String Id=Tid.getText();
        String Name=Tname1.getText();
        String Degree=degree.getText();
        String Salary=Tsalary.getText();
  
   
        
        Teacher t=new Teacher();
                
        
        t.setNationalID(Id);
        t.setName(Name);
        t.setDegree(Degree);
        t.setSalary(Salary);
        
         TeacherDB db=new TeacherDB();
         db.UpdateTeacher(t);
         JOptionPane.showMessageDialog(this,t+"Row Created" );
    }//GEN-LAST:event_TupdateActionPerformed

    private void TdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdeleteActionPerformed
        // TODO add your handling code here:
        String Id=Tid.getText();
        String Name=Tname1.getText();
        String Degree=degree.getText();
        String Salary=Tsalary.getText();
  
   
        
        Teacher t=new Teacher();
                
        
        t.setNationalID(Id);
        t.setName(Name);
        t.setDegree(Degree);
        t.setSalary(Salary);
        
         TeacherDB db=new TeacherDB();
         db.DeleteTeacher(t);
         JOptionPane.showMessageDialog(this,t+"Row Created" );
    }//GEN-LAST:event_TdeleteActionPerformed

    private void CcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcreateActionPerformed
        // TODO add your handling code here:
        String Code=Ccode.getText();
        String Name=CName.getText();
      
       
  
   
        
       Course c=new Course();
                
        
        c.setCid(Code);
        c.setName(Name);
      
        
        CoursesDB db=new CoursesDB();
        db.saveCourse(c);
        
         JOptionPane.showMessageDialog(this,c+"Row Created" );
         comboCourse();
    }//GEN-LAST:event_CcreateActionPerformed

    private void CupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CupdateActionPerformed
        // TODO add your handling code here:
        String Code=Ccode.getText();
        String Name=CName.getText();
      
       
  
   
        
       Course c=new Course();
                
        
        c.setCid(Code);
        c.setName(Name);
      
        
        CoursesDB db=new CoursesDB();
        db.Cupdate(c);
        
         JOptionPane.showMessageDialog(this,c+"Row Created" );
    }//GEN-LAST:event_CupdateActionPerformed

    private void CdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdeleteActionPerformed
        // TODO add your handling code here:
        
        String Code=Ccode.getText();
        String Name=CName.getText();
      
       
  
   
        
       Course c=new Course();
                
        
        c.setCid(Code);
        c.setName(Name);
      
        
        
        CoursesDB db=new CoursesDB();
        db.CDelete(c);
        
         JOptionPane.showMessageDialog(this,c+"Row Created" );
    }//GEN-LAST:event_CdeleteActionPerformed

    private void CreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreadActionPerformed
        // TODO add your handling code here:
        CoursesDB db=new CoursesDB();
         List<Course> ls=new ArrayList<>();
         ls=db.CDisplay();
         DefaultTableModel model= new DefaultTableModel();
         Object cols[] = new Object[2];
         cols[0]="CourseCode";
         cols[1]="Name";
       
        
         model.setColumnIdentifiers(cols);
       for(Course c:ls){
       Object row[]=new Object[3];
                  row[0]=c.getCid();
                  row[1]=c.getName();
                
                  
                  model.addRow(row);
       }
       Ctable.setModel(model);
    }//GEN-LAST:event_CreadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String Id=Fid.getText();
        String Name=Fname.getText();
        
       Faculty f=new Faculty();
        
        f.setId(Id);
        f.setName(Name);
        
        FacultyDB db=new FacultyDB();
        db.saveFaculty(f);
        changedptCombo();
        JOptionPane.showMessageDialog(this, f+"INSERTED");
        
        
        
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FacultyDB db=new FacultyDB();
        List<Faculty> ls=new ArrayList<>();
        ls=db.Display();

        DefaultTableModel Model=new DefaultTableModel();
        Object cols[]=new Object[2];
        cols[0]="ID";
        cols[1]="Name";

        Model.setColumnIdentifiers(cols);

        for(Faculty f:ls){
            Object rows[]=new Object[2];
            rows[0]=f.getId();
            rows[1]=f.getName();

            Model.addRow(rows);

        }
        Ftable.setModel(Model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcreateActionPerformed
        // TODO add your handling code here:
         String Id=Did.getText();
        String Name=Dname.getText();
        
       Departments d=new Departments();
        FacultyDB dao = new FacultyDB();
        d.setId(Id);
        d.setName(Name);
//        Combo1.getSelectedIndex();
        d.setFaculty(dao.Display().get(Combo1.getSelectedIndex()));
        DepartmentDB db=new DepartmentDB();
        db.saveDepartment(d);
        combobox();
        JOptionPane.showMessageDialog(this, d+"INSERTED");
       
    }//GEN-LAST:event_DcreateActionPerformed

    private void DreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DreadActionPerformed
        // TODO add your handling code here:
         DepartmentDB db=new DepartmentDB();
        List<Departments> ls=new ArrayList<>();
        ls=db.DisplayD();

        DefaultTableModel Model=new DefaultTableModel();
        Object cols[]=new Object[2];
        cols[0]="ID";
        cols[1]="Name";

        Model.setColumnIdentifiers(cols);

        for(Departments f:ls){
            Object rows[]=new Object[2];
            rows[0]=f.getId();
            rows[1]=f.getName();

            Model.addRow(rows);

        }
        Dtable.setModel(Model);
    }//GEN-LAST:event_DreadActionPerformed

    private void DupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DupdateActionPerformed
        // TODO add your handling code here:
         String Id=Did.getText();
        String Name=Dname.getText();
        
       Departments d=new Departments();
        
        d.setId(Id);
        d.setName(Name);
        
        DepartmentDB db=new DepartmentDB();
        db.UpdateDepart(d);
        JOptionPane.showMessageDialog(this, d+"INSERTED");
    }//GEN-LAST:event_DupdateActionPerformed

    private void DdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DdeleteActionPerformed
        // TODO add your handling code here:
         String Id=Did.getText();
        String Name=Dname.getText();
        
       Departments d=new Departments();
        
        d.setId(Id);
        d.setName(Name);
        
        DepartmentDB db=new DepartmentDB();
        db.DeleteDepart(d);
        JOptionPane.showMessageDialog(this, d+"INSERTED");
    }//GEN-LAST:event_DdeleteActionPerformed

    private void Combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo3ActionPerformed

    private void Tname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tname1ActionPerformed

    private void stSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stSearchActionPerformed
        // TODO add your handling code here:
        
        String id=studentId.getText();
        StudentDB da= new StudentDB();
        
        Student st = new Student();
        st=da.findByID(id);
        
        DefaultTableModel Model=new DefaultTableModel();
        Object cols[]=new Object[2];
        cols[0]="Course_ID";
        cols[1]="Course_Name";

        Model.setColumnIdentifiers(cols);

        for(Course f:st.getRegCourses()){
            Object rows[]=new Object[2];
            rows[0]=f.getCid();
            rows[1]=f.getName();

            Model.addRow(rows);

        }
        StudentCourseResult.setModel(Model);
        
        
    }//GEN-LAST:event_stSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }
    public void changedptCombo(){
    
    FacultyDB db=new FacultyDB();
    List<Faculty> ls=new ArrayList<>();
    
    ls=db.Display();
    Combo1.removeAllItems();
    for(Faculty f:ls){
    
    Combo1.addItem(f.getName());
    
    
    }
    
    }
    public void combobox(){
    
    DepartmentDB db=new DepartmentDB();
    List<Departments> ls=new ArrayList<>();
    ls=db.DisplayD();
    
    for(Departments d:ls){
    
    Combo2.addItem(d.getName());
    }
        
    }
    public void comboCourse(){
    CoursesDB db=new CoursesDB();
    List<Course> ls= new ArrayList<>();
    ls=db.CDisplay();
    
    for(Course c:ls){
    
    Combo3.addItem(c.getName());
    Combo4.addItem(c.getName());
    
    }
    
    
    
    }
    
    
//    public void change
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CName;
    private javax.swing.JTextField Ccode;
    private javax.swing.JButton Ccreate;
    private javax.swing.JButton Cdelete;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JComboBox<String> Combo3;
    private javax.swing.JComboBox<String> Combo4;
    private javax.swing.JButton Cread;
    private javax.swing.JTable Ctable;
    private javax.swing.JButton Cupdate;
    private javax.swing.JButton Dcreate;
    private javax.swing.JButton Ddelete;
    private javax.swing.JButton Delete;
    private javax.swing.JTabbedPane Department;
    private javax.swing.JTextField Did;
    private javax.swing.JTextField Dname;
    private javax.swing.JButton Dread;
    private javax.swing.JTable Dtable;
    private javax.swing.JButton Dupdate;
    private javax.swing.JTextField Fid;
    private javax.swing.JTextField Fname;
    private javax.swing.JTable Ftable;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Read;
    private javax.swing.JButton Screate;
    private javax.swing.JTextField Sid;
    private javax.swing.JTextField Sname;
    private javax.swing.JTable Stable;
    private javax.swing.JTable StudentCourseResult;
    private javax.swing.JButton Tcreate;
    private javax.swing.JButton Tdelete;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tname1;
    private javax.swing.JButton Tread;
    private javax.swing.JTextField Tsalary;
    private javax.swing.JTable Ttable;
    private javax.swing.JButton Tupdate;
    private javax.swing.JButton Update;
    private javax.swing.JTextField degree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel registration;
    private javax.swing.JButton stSearch;
    private javax.swing.JTextField studentId;
    // End of variables declaration//GEN-END:variables
}
